name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.**"
      - "*.*.*.**"

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
        with:
          tool: git-cliff
      - run: git cliff -o CHANGELOG_${{ github.ref_name }}.md $(git tag -l | sort -V | tail -n -2 | head -n -1)..HEAD
      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          body_path: CHANGELOG_${{ github.ref_name }}.md
          token: ${{ secrets.GITHUB_TOKEN }}

  bin-amd64-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - run: |
          cd target/x86_64-unknown-linux-gnu/release/
          tar -cJvf hddfancontrol_${{ github.ref_name }}_amd64.tar.xz hddfancontrol
      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: target/x86_64-unknown-linux-gnu/release/hddfancontrol*.tar.xz
          token: ${{ secrets.GITHUB_TOKEN }}

  deb-amd64-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - run: |
          mkdir -p target/man
          cargo run --features generate-extras -- gen-man-pages target/man
          rm target/man/hddfancontrol-gen-*
          gzip -9 target/man/*.1
          mkdir -p target/shell-completions
          cargo run --features generate-extras -- gen-shell-completions target/shell-completions
      - uses: taiki-e/install-action@7be9fd86bd1707236395105d6e9329dd1511a7e1 # v2.79.0
        with:
          tool: cargo-deb
      - run: cargo deb --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
      - uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          files: target/x86_64-unknown-linux-gnu/debian/hddfancontrol_*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
